apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-private
  labels:
    app: nginx-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-private
  template:
    metadata:
      labels:
        app: nginx-private
    spec:
      imagePullSecrets:
        - name: my-registry-secret         
      containers:
        - name: nginx
          image: swr.cn-north-4.myhuaweicloud.com/swr-qin/nginx:v2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-private-svc
spec:
  selector:
    app: nginx-private
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
